/**
 * Optional: append active product URLs to public/sitemap.xml.
 * Needs VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY (or SUPABASE_*).
 * Missing env → quiet static-only (local dev).
 * Env present + 0 products → fail unless ALLOW_EMPTY_SITEMAP=1 (staging hatch).
 *
 * Origin is pinned to production (https://heven.fun). VITE_SITE_URL may still
 * point at staging until the heven.fun cutover — that is SEO-6 / deploy ops.
 *
 * Run: node scripts/generate-sitemap.mjs
 * Or:  npm run sitemap
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createClient } from '@supabase/supabase-js';
import { loadEnvFile } from './load-env.mjs';

loadEnvFile();

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'public', 'sitemap.xml');
const ORIGIN = 'https://heven.fun';

const STATIC = [
  ['/', 'daily', '1.0'],
  ['/store', 'daily', '0.9'],
  ['/subscriptions', 'weekly', '0.8'],
  ['/gift-cards', 'weekly', '0.8'],
  ['/about', 'monthly', '0.5'],
  ['/privacy', 'yearly', '0.3'],
  ['/terms', 'yearly', '0.3'],
  ['/updates', 'weekly', '0.4'],
];

function urlRow(loc, changefreq, priority) {
  return `  <url><loc>${ORIGIN}${loc}</loc><changefreq>${changefreq}</changefreq><priority>${priority}</priority></url>`;
}

const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const key = process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;
const allowEmpty = process.env.ALLOW_EMPTY_SITEMAP === '1';

let productRows = [];
if (url && key) {
  const sb = createClient(url, key);
  const { data, error } = await sb
    .from('products')
    .select('slug')
    .eq('status', 'active')
    .not('slug', 'is', null)
    .limit(2000);
  if (error) {
    console.error('generate-sitemap: product query failed:', error.message);
    if (!allowEmpty) {
      console.error(
        'generate-sitemap: refusing empty product sitemap (set ALLOW_EMPTY_SITEMAP=1 to override)',
      );
      process.exit(1);
    }
  } else {
    productRows = data ?? [];
  }

  if (productRows.length === 0 && !allowEmpty) {
    console.error(
      'generate-sitemap: Supabase env present but 0 active products — refusing to ship a product-less sitemap. Set ALLOW_EMPTY_SITEMAP=1 for staging.',
    );
    process.exit(1);
  }
} else {
  console.warn('generate-sitemap: no Supabase env — writing static routes only');
}

const lines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by scripts/generate-sitemap.mjs — static routes + active products when env present. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...STATIC.map(([loc, f, p]) => urlRow(loc, f, p)),
  ...productRows
    .map((r) => String(r.slug || '').trim())
    .filter(Boolean)
    .map((slug) => urlRow(`/product/${encodeURIComponent(slug)}`, 'weekly', '0.7')),
  '</urlset>',
  '',
];

fs.writeFileSync(out, lines.join('\n'), 'utf8');
console.log(`generate-sitemap: ${STATIC.length} static + ${productRows.length} products → public/sitemap.xml`);
